#!/usr/bin/env node
const { program } = require("commander");

const k8s = require('@kubernetes/client-node');


program
  .argument('[cluster]', 'Target cluster (sc | wc)', "sc")
  .argument('[component]', 'Target component : base | ingress | opensearch', "base")
  .option('--health', 'Check ingress health', false)
  .action((cluster, component, options) => {
    console.log(`Running ${component} tests against ${cluster} cluster`);
    if (component == 'ingress') {

      if (options.health) {
        console.log("Checking ingress health ...")
        const kc = new k8s.KubeConfig();
        kc.loadFromFile(`${process.env.CK8S_CONFIG_PATH}/.state/kube_config_${cluster}.yaml`)
        
        const k8sApi = kc.makeApiClient(k8s.AppsV1Api);
        k8sApi.readNamespacedDaemonSetStatus("ingress-nginx-controller", "ingress-nginx").then((res) => {
          if (res.body.status.numberReady != res.body.status.currentNumberScheduled)  {
            console.log('[ERROR] Some ingress-nginx pods are not ready')
          } else {
            console.log('[SUCCESS] All nginx pods are ready')
          }
        })
      }
      }
  });

program.parse(process.argv);