#!/usr/bin/env node
// const { Command } = require('commander');
const { program } = require("commander");

program
  .name('ck8s')
  .description('CK8S CLI')
  .version('0.1.0');

program.command("test", "Test the applications");
program.command('init', "Initialize the config path")
program.command('bootstrap',"Bootstrap the cluster")
program.command('apps', "Deploy the applications")

program.parse(process.argv);